// Generates db/seed.sql: resources (extracted from the hub page), tasks, and
// the monthly budget (from the budget calculator spec).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// --- pull the RESOURCES array out of the hub page (single source of truth) ---
const page = fs.readFileSync(path.join(root, "160akley", "index.html"), "utf8");
const startTok = "var RESOURCES = ";
const start = page.indexOf(startTok);
const rest = page.slice(start + startTok.length);
const end = rest.indexOf("\n    ];");
const literal = rest.slice(0, end) + "\n    ]";
const RESOURCES = eval(literal); // our own content

const q = (v) => (v == null ? "NULL" : "'" + String(v).replace(/'/g, "''") + "'");
const now = Date.now();
let lines = [];
let n = 0;
for (const g of RESOURCES) {
  let s = 0;
  for (const it of g.items) {
    const id = "r" + (++n).toString(36).padStart(3, "0");
    lines.push(
      `INSERT INTO resources (id,category,cat_subt,name,phones,email,web,address,note,flag,created_by,created_at,sort) VALUES (` +
      [q(id), q(g.cat), q(g.subt || null), q(it.n), q(JSON.stringify(it.p || [])), q(it.e || null), q(it.w || null), q(it.a || null), q(it.note || null), q(it.flag || null), q("seed"), now, s++].join(",") + `);`
    );
  }
}

// --- tasks ---
const tasks = [
  ["Retain a closing attorney (Jane Krochmalny is in Guilford)", "Legal", "Today", "week", 0],
  ["Order a radon test", "Inspect", "Sat", "week", 0],
  ["Well water potability test", "Water", "This wk", "week", 0],
  ["Schedule chimney sweep & inspection", "Wood", "Jul 15", "soon", 0],
  ["Septic inspection & pump-out", "Septic", "Jul", "soon", 0],
  ["Set up Green Mountain Power account", "Power", "Jul", "soon", 0],
  ["Book Starlink install", "Internet", "Jun 30", "soon", 1],
  ["Pay off credit-card balance from savings", "Money", "Jun", "soon", 1],
];
tasks.forEach((t, i) => {
  const id = "t" + (i + 1).toString(36).padStart(3, "0");
  lines.push(
    `INSERT INTO tasks (id,text,area,due,grp,done,created_by,created_at,sort) VALUES (` +
    [q(id), q(t[0]), q(t[1]), q(t[2]), q(t[3]), t[4], q("seed"), now, i].join(",") + `);`
  );
});

// --- monthly budget (from budget-calculator-spec) ---
const budget = [
  ["Loan interest", "fixed", 2013, "Interest-only family loan @ 4.6% AFR on $525,000"],
  ["Property tax", "fixed", 917, "$11,000/yr"],
  ["Homeowners insurance", "fixed", 183, "$2,200/yr"],
  ["Electricity", "fixed", 130, "Green Mountain Power, incl. well pump"],
  ["Internet (Starlink)", "fixed", 120, null],
  ["Heating oil", "fixed", 60, "Hot water only — heat is wood"],
  ["Groceries", "living", 1350, "Brattleboro Food Co-op"],
  ["Cafes & restaurants", "living", 400, null],
  ["Auto", "living", 330, "Insurance + fuel + reserve"],
  ["Household & shopping", "living", 400, null],
  ["Subscriptions & gym", "living", 145, null],
  ["Health & misc", "living", 100, null],
];
budget.forEach((b, i) => {
  const id = "b" + (i + 1).toString(36).padStart(3, "0");
  lines.push(
    `INSERT INTO budget_lines (id,label,grp,amount,note,sort) VALUES (` +
    [q(id), q(b[0]), q(b[1]), b[2], q(b[3]), i].join(",") + `);`
  );
});
lines.push(`INSERT INTO budget_meta (key,num,txt) VALUES ('net_income',6625,'Semi-monthly net pay, $3,312.27 x 2');`);
lines.push(`INSERT INTO budget_meta (key,num,txt) VALUES ('jan_step',688,'Ex-partner off insurance, from Jan 2027');`);

const sql = "-- generated by db/gen-seed.mjs\n" + lines.join("\n") + "\n";
fs.writeFileSync(path.join(__dirname, "seed.sql"), sql);
console.log("wrote db/seed.sql:", RESOURCES.reduce((a, g) => a + g.items.length, 0), "resources,", tasks.length, "tasks,", budget.length, "budget lines");
